import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useBooking } from '../context/BookingContext';
import { useAuth } from '../context/AuthContext';
import SeatMap from '../components/SeatMap';

function Booking() {
  const navigate = useNavigate();
  const { bookingData, updateBooking, clearBooking } = useBooking();
  const { user } = useAuth();

  const [step, setStep] = useState(1);
  const [selectedSeats, setSelectedSeats] = useState([]);
  const [customerName, setCustomerName] = useState('');

  // New States for Backend Integration
  const [paymentMethod, setPaymentMethod] = useState('card');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState(null);

  // Check if the user is staff (employee or admin)
  const isStaff = user?.role === 'employee' || user?.role === 'admin';

  if (!bookingData.selectedMovie) {
    navigate('/');
    return null;
  }

  const pricePerSeat = bookingData.selectedShowtime?.pricePerSeat || 12;
  const totalPrice = selectedSeats.length * pricePerSeat;

  const handleSeatsChange = (seats) => {
    setSelectedSeats(seats);
    updateBooking({ selectedSeats: seats, totalPrice: seats.length * pricePerSeat });
  };

  const handleContinue = () => {
    if (step < 4) {
      setStep(step + 1);
      setError(null); // Clear errors when moving between steps
    } else {
      handleConfirmBooking();
    }
  };

  const handleConfirmBooking = async () => {
    setIsSubmitting(true);
    setError(null);

    try {
      // 1. Call your real Cloudflare backend API
      const response = await fetch('/api/bookings', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          showtimeId: bookingData.selectedShowtime.id,
          seats: selectedSeats,
          totalPrice: totalPrice,
          paymentMethod: paymentMethod
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to confirm booking.');
      }

      // 2. Build the ticket payload to pass to the Success Screen
      const ticket = {
        id: data.bookingId, // Use the real ID generated by the database
        soldById: isStaff ? user.id : null,
        customerName: isStaff ? customerName : user.name,
        movieTitle: bookingData.selectedMovie.title,
        showtime: `${bookingData.selectedDate} ${bookingData.selectedTime}`,
        theater: bookingData.selectedShowtime.theater,
        seats: selectedSeats,
        totalPrice,
        paymentMethod,
        status: 'confirmed',
      };

      clearBooking();
      navigate('/success', { state: { booking: ticket, isStaffSale: isStaff } });

    } catch (err) {
      console.error("Checkout Error:", err);
      setError(err.message);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
      <div className="min-h-screen bg-gradient-to-b from-gray-900 to-gray-800 py-8">
        <div className="max-w-6xl mx-auto px-4">
          {/* Progress Steps */}
          <div className="mb-8">
            <div className="flex justify-between items-center">
              {[1, 2, 3, 4].map((s) => (
                  <React.Fragment key={s}>
                    <div
                        className={`w-10 h-10 rounded-full flex items-center justify-center font-bold transition ${
                            step >= s ? 'bg-amber-600 text-white' : 'bg-gray-700 text-gray-400'
                        }`}
                    >
                      {s}
                    </div>
                    {s < 4 && (
                        <div
                            className={`flex-1 h-1 mx-2 transition ${step > s ? 'bg-amber-600' : 'bg-gray-700'}`}
                        ></div>
                    )}
                  </React.Fragment>
              ))}
            </div>
            <div className="flex justify-between text-gray-400 text-xs mt-2">
              <span>Seats</span>
              <span>Payment</span>
              <span>Confirmation</span>
              <span>Complete</span>
            </div>
          </div>

          {/* Content */}
          <div className="bg-gray-800 rounded-lg p-6 dark:bg-gray-900 mb-8 shadow-xl border border-gray-700">
            {step === 1 && (
                <>
                  <h2 className="text-white text-2xl font-bold mb-6">Step 1: Select Seats</h2>
                  <SeatMap
                      theater={bookingData.selectedShowtime?.theater}
                      onSeatsChange={handleSeatsChange}
                      selectedSeats={selectedSeats}
                      pricePerSeat={pricePerSeat}
                  />
                </>
            )}

            {step === 2 && (
                <>
                  <h2 className="text-white text-2xl font-bold mb-6">Step 2: {isStaff ? 'Customer Info & Payment' : 'Payment Options'}</h2>
                  <div className="bg-gray-700 rounded-lg p-6 dark:bg-gray-800 border border-gray-600">

                    {/* Customer name input for staff sales */}
                    {isStaff && (
                        <div className="mb-8 border-b border-gray-600 pb-6">
                          <label className="block text-gray-300 text-sm font-medium mb-2">Customer Name</label>
                          <input
                              type="text"
                              value={customerName}
                              onChange={(e) => setCustomerName(e.target.value)}
                              placeholder="Enter customer name"
                              className="w-full bg-gray-600 text-white px-4 py-3 rounded-lg focus:outline-none focus:ring-2 focus:ring-amber-600"
                              required
                          />
                        </div>
                    )}

                    {/* New Payment Selector */}
                    <div className="mb-6">
                      <label className="block text-gray-300 text-sm font-medium mb-3">Select Payment Method</label>
                      <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                        <button
                            type="button"
                            onClick={() => setPaymentMethod('card')}
                            className={`p-4 rounded-lg border font-bold text-center transition ${paymentMethod === 'card' ? 'bg-amber-600 border-amber-600 text-white' : 'bg-gray-800 border-gray-600 text-gray-400 hover:text-white'}`}
                        >
                          💳 Credit Card
                        </button>
                        <button
                            type="button"
                            onClick={() => setPaymentMethod('online-bank')}
                            className={`p-4 rounded-lg border font-bold text-center transition ${paymentMethod === 'online-bank' ? 'bg-amber-600 border-amber-600 text-white' : 'bg-gray-800 border-gray-600 text-gray-400 hover:text-white'}`}
                        >
                          🏦 Online Banking
                        </button>
                        {isStaff && (
                            <button
                                type="button"
                                onClick={() => setPaymentMethod('cash')}
                                className={`p-4 rounded-lg border font-bold text-center transition ${paymentMethod === 'cash' ? 'bg-amber-600 border-amber-600 text-white' : 'bg-gray-800 border-gray-600 text-gray-400 hover:text-white'}`}
                            >
                              💵 Cash (Counter)
                            </button>
                        )}
                      </div>
                    </div>

                    {/* Dummy Card Input - Only show if 'card' is selected */}
                    {paymentMethod === 'card' && (
                        <div className="mt-8 pt-6 border-t border-gray-600 animate-in fade-in slide-in-from-top-4">
                          <div className="mb-4">
                            <label className="block text-gray-300 text-sm font-medium mb-2">Card Number</label>
                            <input
                                type="text"
                                placeholder="1234 5678 9012 3456"
                                className="w-full bg-gray-600 text-white px-4 py-3 rounded-lg focus:outline-none focus:ring-2 focus:ring-amber-600"
                            />
                          </div>
                          <div className="grid grid-cols-2 gap-4">
                            <div>
                              <label className="block text-gray-300 text-sm font-medium mb-2">Expiry</label>
                              <input
                                  type="text"
                                  placeholder="MM/YY"
                                  className="w-full bg-gray-600 text-white px-4 py-3 rounded-lg focus:outline-none focus:ring-2 focus:ring-amber-600"
                              />
                            </div>
                            <div>
                              <label className="block text-gray-300 text-sm font-medium mb-2">CVV</label>
                              <input
                                  type="text"
                                  placeholder="123"
                                  className="w-full bg-gray-600 text-white px-4 py-3 rounded-lg focus:outline-none focus:ring-2 focus:ring-amber-600"
                              />
                            </div>
                          </div>
                        </div>
                    )}

                    {/* Online Banking QR Code */}
                    {paymentMethod === 'online-bank' && (
                        <div className="mt-8 pt-6 border-t border-gray-600 animate-in fade-in slide-in-from-top-4 flex flex-col items-center text-center">
                          <p className="text-white font-bold mb-4">Scan to Pay via Online Banking</p>
                          <div className="bg-white p-4 rounded-xl shadow-lg mb-4 inline-block">
                            {/* Generates a live dummy QR code containing the booking ID and amount */}
                            <img
                                src={`https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=PAY-CINEBOOK-${totalPrice}`}
                                alt="Payment QR Code"
                                className="w-48 h-48"
                            />
                          </div>
                          <p className="text-gray-400 text-sm mb-1">Amount Due: <span className="text-amber-500 font-bold">₱{totalPrice}</span></p>
                          <p className="text-gray-500 text-xs">Scan with GCash, Maya, or your preferred banking app to proceed.</p>
                        </div>
                    )}
                  </div>
                </>
            )}

            {step === 3 && (
                <>
                  <h2 className="text-white text-2xl font-bold mb-6">Step 3: Confirmation</h2>
                  <div className="space-y-4">
                    <div className="bg-gray-700 rounded-lg p-4 dark:bg-gray-800 border border-gray-600">
                      <p className="text-gray-400 text-sm">Movie</p>
                      <p className="text-white font-bold text-lg">{bookingData.selectedMovie.title}</p>
                    </div>
                    <div className="grid grid-cols-3 gap-4">
                      <div className="bg-gray-700 rounded-lg p-4 dark:bg-gray-800 border border-gray-600">
                        <p className="text-gray-400 text-sm">Date</p>
                        <p className="text-white font-bold">{bookingData.selectedDate}</p>
                      </div>
                      <div className="bg-gray-700 rounded-lg p-4 dark:bg-gray-800 border border-gray-600">
                        <p className="text-gray-400 text-sm">Time</p>
                        <p className="text-white font-bold">{bookingData.selectedTime}</p>
                      </div>
                      <div className="bg-gray-700 rounded-lg p-4 dark:bg-gray-800 border border-gray-600">
                        <p className="text-gray-400 text-sm">Theater</p>
                        <p className="text-white font-bold">{bookingData.selectedShowtime.theater}</p>
                      </div>
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="bg-gray-700 rounded-lg p-4 dark:bg-gray-800 border border-gray-600">
                        <p className="text-gray-400 text-sm">Seats</p>
                        <p className="text-white font-bold text-lg">{selectedSeats.join(', ')}</p>
                      </div>
                      <div className="bg-gray-700 rounded-lg p-4 dark:bg-gray-800 border border-gray-600">
                        <p className="text-gray-400 text-sm">Payment Method</p>
                        <p className="text-white font-bold text-lg capitalize">{paymentMethod.replace('-', ' ')}</p>
                      </div>
                    </div>
                  </div>
                </>
            )}

            {step === 4 && (
                <>
                  <h2 className="text-white text-2xl font-bold mb-6">Step 4: Review</h2>

                  {/* Display error message if the API call fails */}
                  {error && (
                      <div className="bg-red-500/10 border border-red-500 text-red-500 p-4 rounded-lg mb-6 text-center">
                        <p className="font-bold">Booking Failed</p>
                        <p className="text-sm mt-1">{error}</p>
                      </div>
                  )}

                  <div className="text-center">
                    <div className="bg-gray-700 rounded-lg p-8 dark:bg-gray-800 mb-6 border border-gray-600">
                      <p className="text-gray-400 text-sm mb-2">Total Amount</p>
                      <p className="text-white text-5xl font-bold text-amber-600">₱{totalPrice}</p>
                    </div>
                    <p className="text-gray-300">
                      {isStaff ? 'Ready to complete this sale?' : 'Ready to complete your purchase?'}
                    </p>
                  </div>
                </>
            )}
          </div>

          {/* Navigation */}
          <div className="flex justify-between">
            <button
                onClick={() => setStep(Math.max(1, step - 1))}
                disabled={step === 1 || isSubmitting}
                className="px-6 py-3 bg-gray-700 text-white rounded-lg hover:bg-gray-600 transition disabled:opacity-50 disabled:cursor-not-allowed font-bold"
            >
              Back
            </button>

            <button
                onClick={handleContinue}
                disabled={
                    (step === 1 && selectedSeats.length === 0) ||
                    (step === 2 && isStaff && !customerName.trim()) ||
                    isSubmitting
                }
                className="px-6 py-3 bg-amber-600 text-white rounded-lg hover:bg-amber-700 transition disabled:opacity-50 disabled:cursor-not-allowed font-bold flex items-center justify-center min-w-[140px]"
            >
              {isSubmitting ? (
                  <span className="animate-pulse">Processing...</span>
              ) : (
                  step === 4 ? (isStaff ? 'Confirm Sale' : 'Confirm Purchase') : 'Continue'
              )}
            </button>
          </div>
        </div>
      </div>
  );
}

export default Booking;